package com.stream.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.stream.dao.DetailInfo;
import com.stream.dao.SourceInfo;
import com.stream.dao.DownloadInfo;
import com.stream.dao.Favorite;
import com.stream.dao.Suggestion;

import com.stream.dao.DetailDao;
import com.stream.dao.SourceDao;
import com.stream.dao.DownloadDao;
import com.stream.dao.FavoriteDao;
import com.stream.dao.SuggestionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig detailDaoConfig;
    private final DaoConfig sourceDaoConfig;
    private final DaoConfig downloadDaoConfig;
    private final DaoConfig favoriteDaoConfig;
    private final DaoConfig suggestionDaoConfig;

    private final DetailDao detailDao;
    private final SourceDao sourceDao;
    private final DownloadDao downloadDao;
    private final FavoriteDao favoriteDao;
    private final SuggestionDao suggestionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        detailDaoConfig = daoConfigMap.get(DetailDao.class).clone();
        detailDaoConfig.initIdentityScope(type);

        sourceDaoConfig = daoConfigMap.get(SourceDao.class).clone();
        sourceDaoConfig.initIdentityScope(type);

        downloadDaoConfig = daoConfigMap.get(DownloadDao.class).clone();
        downloadDaoConfig.initIdentityScope(type);

        favoriteDaoConfig = daoConfigMap.get(FavoriteDao.class).clone();
        favoriteDaoConfig.initIdentityScope(type);

        suggestionDaoConfig = daoConfigMap.get(SuggestionDao.class).clone();
        suggestionDaoConfig.initIdentityScope(type);

        detailDao = new DetailDao(detailDaoConfig, this);
        sourceDao = new SourceDao(sourceDaoConfig, this);
        downloadDao = new DownloadDao(downloadDaoConfig, this);
        favoriteDao = new FavoriteDao(favoriteDaoConfig, this);
        suggestionDao = new SuggestionDao(suggestionDaoConfig, this);

        registerDao(DetailInfo.class, detailDao);
        registerDao(SourceInfo.class, sourceDao);
        registerDao(DownloadInfo.class, downloadDao);
        registerDao(Favorite.class, favoriteDao);
        registerDao(Suggestion.class, suggestionDao);
    }
    
    public void clear() {
        detailDaoConfig.getIdentityScope().clear();
        sourceDaoConfig.getIdentityScope().clear();
        downloadDaoConfig.getIdentityScope().clear();
        favoriteDaoConfig.getIdentityScope().clear();
        suggestionDaoConfig.getIdentityScope().clear();
    }

    public DetailDao getDetailDao() {
        return detailDao;
    }

    public SourceDao getSourceDao() {
        return sourceDao;
    }

    public DownloadDao getDownloadDao() {
        return downloadDao;
    }

    public FavoriteDao getFavoriteDao() {
        return favoriteDao;
    }

    public SuggestionDao getSuggestionDao() {
        return suggestionDao;
    }

}
