package com.stream.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "hs_detail_info".
 */
public class DetailInfo {

    private String token;
    /** Not-null value. */
    private String video_title;
    private String alternative_name;
    private String offering_date;
    private String subtitle_path;
    private String detail_url;

    public DetailInfo() {
    }

    public DetailInfo(String token) {
        this.token = token;
    }

    public DetailInfo(String token, String video_title, String alternative_name, String offering_date, String subtitle_path, String detail_url) {
        this.token = token;
        this.video_title = video_title;
        this.alternative_name = alternative_name;
        this.offering_date = offering_date;
        this.subtitle_path = subtitle_path;
        this.detail_url = detail_url;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    /** Not-null value. */
    public String getVideo_title() {
        return video_title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideo_title(String video_title) {
        this.video_title = video_title;
    }

    public String getAlternative_name() {
        return alternative_name;
    }

    public void setAlternative_name(String alternative_name) {
        this.alternative_name = alternative_name;
    }

    public String getOffering_date() {
        return offering_date;
    }

    public void setOffering_date(String offering_date) {
        this.offering_date = offering_date;
    }

    public String getSubtitle_path() {
        return subtitle_path;
    }

    public void setSubtitle_path(String subtitle_path) {
        this.subtitle_path = subtitle_path;
    }

    public String getDetail_url() {
        return detail_url;
    }

    public void setDetail_url(String detail_url) {
        this.detail_url = detail_url;
    }

}
