package com.stream.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "hs_dowanload_info".
 */
public class DownloadInfo {

    /** Not-null value. */
    private String token;
    private String title;
    private String thumb;
    private String source_url;
    private String url;
    private int state;
    private long time;

    private long speed;
    private long total;
    private long finished;

    public long getSpeed() {
        return speed;
    }

    public void setSpeed(long speed) {
        this.speed = speed;
    }

    public long getTotal() {
        return total;
    }

    public void setTotal(long total) {
        this.total = total;
    }

    public long getFinished() {
        return finished;
    }

    public void setFinished(long finished) {
        this.finished = finished;
    }

    public DownloadInfo() {
    }

    public DownloadInfo(String token) {
        this.token = token;
    }

    public DownloadInfo(String token, String title, String thumb, String source_url, String url, int state, long time) {
        this.token = token;
        this.title = title;
        this.thumb = thumb;
        this.source_url = source_url;
        this.url = url;
        this.state = state;
        this.time = time;
    }

    /** Not-null value. */
    public String getToken() {
        return token;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToken(String token) {
        this.token = token;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getThumb() {
        return thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    public String getSourceUrl() {
        return source_url;
    }

    public void setSourceUrl(String source_url) {
        this.source_url = source_url;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

}
