package com.stream.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "hs_favorites".
 */
public class Favorite {

    /** Not-null value. */
    private String token;
    private String title;
    private String thumb;
    private String source_url;
    private String video_url;
    private long time;

    public Favorite() {
    }

    public Favorite(String token) {
        this.token = token;
    }

    public Favorite(String token, String title, String thumb, String source_url, String video_url, long time) {
        this.token = token;
        this.title = title;
        this.thumb = thumb;
        this.source_url = source_url;
        this.video_url = video_url;
        this.time = time;
    }

    /** Not-null value. */
    public String getToken() {
        return token;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToken(String token) {
        this.token = token;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getThumb() {
        return thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    public String getSourceUrl() {
        return source_url;
    }

    public void setSourceUrl(String source_url) {
        this.source_url = source_url;
    }

    public String getVideoUrl() {
        return video_url;
    }

    public void setVideoUrl(String video_url) {
        this.video_url = video_url;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

}
