package com.stream.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.stream.dao.Favorite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "hs_favorites".
*/
public class FavoriteDao extends AbstractDao<Favorite, String> {

    public static final String TABLENAME = "hs_favorites";

    /**
     * Properties of entity Favorite.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Token = new Property(0, String.class, "token", true, "TOKEN");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Thumb = new Property(2, String.class, "thumb", false, "THUMB");
        public final static Property Source_url = new Property(3, String.class, "source_url", false, "SOURCE_URL");
        public final static Property Video_url = new Property(4, String.class, "video_url", false, "VIDEO_URL");
        public final static Property Time = new Property(5, long.class, "time", false, "TIME");
    };


    public FavoriteDao(DaoConfig config) {
        super(config);
    }
    
    public FavoriteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"hs_favorites\" (" + //
                "\"TOKEN\" TEXT PRIMARY KEY NOT NULL ," + // 0: token
                "\"TITLE\" TEXT," + // 1: title
                "\"THUMB\" TEXT," + // 2: thumb
                "\"SOURCE_URL\" TEXT," + // 3: source_url
                "\"VIDEO_URL\" TEXT," + // 4: video_url
                "\"TIME\" INTEGER NOT NULL );"); // 5: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"hs_favorites\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Favorite entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getToken());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String thumb = entity.getThumb();
        if (thumb != null) {
            stmt.bindString(3, thumb);
        }
 
        String source_url = entity.getSource_url();
        if (source_url != null) {
            stmt.bindString(4, source_url);
        }
 
        String video_url = entity.getVideo_url();
        if (video_url != null) {
            stmt.bindString(5, video_url);
        }
        stmt.bindLong(6, entity.getTime());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Favorite readEntity(Cursor cursor, int offset) {
        Favorite entity = new Favorite( //
            cursor.getString(offset + 0), // token
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // thumb
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // source_url
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // video_url
            cursor.getLong(offset + 5) // time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Favorite entity, int offset) {
        entity.setToken(cursor.getString(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setThumb(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSource_url(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setVideo_url(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTime(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Favorite entity, long rowId) {
        return entity.getToken();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Favorite entity) {
        if(entity != null) {
            return entity.getToken();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
