package com.stream.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "hs_source_info".
 */
public class SourceInfo {

    private Long id;
    /** Not-null value. */
    private String token;
    private String video_title;
    /** Not-null value. */
    private String source_url;
    /** Not-null value. */
    private String source_name;
    /** Not-null value. */
    private String video_url;
    private long upd_time;

    public SourceInfo() {
    }

    public SourceInfo(Long id) {
        this.id = id;
    }

    public SourceInfo(Long id, String token, String video_title, String source_url, String source_name, String video_url, long upd_time) {
        this.id = id;
        this.token = token;
        this.video_title = video_title;
        this.source_url = source_url;
        this.source_name = source_name;
        this.video_url = video_url;
        this.upd_time = upd_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getToken() {
        return token;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToken(String token) {
        this.token = token;
    }

    public String getVideo_title() {
        return video_title;
    }

    public void setVideo_title(String video_title) {
        this.video_title = video_title;
    }

    /** Not-null value. */
    public String getSource_url() {
        return source_url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSource_url(String source_url) {
        this.source_url = source_url;
    }

    /** Not-null value. */
    public String getSource_name() {
        return source_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSource_name(String source_name) {
        this.source_name = source_name;
    }

    /** Not-null value. */
    public String getVideo_url() {
        return video_url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideo_url(String video_url) {
        this.video_url = video_url;
    }

    public long getUpd_time() {
        return upd_time;
    }

    public void setUpd_time(long upd_time) {
        this.upd_time = upd_time;
    }

}
