package com.stream.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "hs_suggestions".
 */
public class Suggestion {

    private int id;
    private String query;
    private Long date;

    public Suggestion() {
    }

    public Suggestion(int id) {
        this.id = id;
    }

    public Suggestion(int id, String query, Long date) {
        this.id = id;
        this.query = query;
        this.date = date;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getQuery() {
        return query;
    }

    public void setQuery(String query) {
        this.query = query;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

}
